language: ruby

rvm:
  - 2.7.2

sudo: false

cache:
  bundler: true

before_install:
  - gem update --system

services:
  - postgresql
  - mysql

env:
  global:
    - CI=true
    - RAILS_ENV=test

  matrix:
    - "DB=postgresql"
    - "DB=mysql"

addons:
  postgresql: "9.5"

before_script:
  - 'if [ $DB = "mysql" ]; then
       mysql -e "create database travis_ci_test;";
     elif [ $2 = "postgres" ]; then
       psql -c "create database travis_ci_test;" -U postgres;
     fi'
  - cp spec/test_app/config/database.$DB.yml.travis spec/test_app/config/database.yml
